name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build
        run: |
          forge build

      - name: Check formatting
        run: |
          forge fmt --check

      - name: Run tests
        run: |
          forge test -vvv